name: Run server tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        NODE_ENV: test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd server && npm ci
    - run: cd server && npm test
    - run: cd client && npm ci
