name: Run server tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        mongodb-version: [4.4]

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
      
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
      
    - name: Use Node.js ${{ matrix.node-version }}
      env:
        NODE_ENV: test
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
<<<<<<< HEAD
    - run: cd server && npm ci
    - run: cd server && npm test
=======


    - run: npm ci
    - run: npm test
>>>>>>> fe5c06068c6b64e99d156003ff1abef444650354
